### ISSUE TITLE
Avatar aspect ratio

### ISSUE THREAD

**Issue by rphenriques** [AuroralH2020/auroral-nm-ui#1]
Avatar in organisation's profile does not keep original aspect ratio if original image is not square.

It looks OK in the "All organisations" listing.

Could be helpful to indicate min and max dimensions and/or aspect ratio on the "Change avatar" action.

**Comment by Joralmi** [comment]
Hello Rui, thank you for letting us know. We will have a look at it

**Comment by Joralmi** [comment]
Fixed issue
